language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
  - "4.0"
  - "5.0"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
script: npm run-script test-cov
after_success:
  - test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter
    < ./coverage/lcov.info
notifications:
  email:
    - snowyu.lee@gmail.com
addons:
  code_climate:
    repo_token:
      secure: "CYoAfkL1/DT7AoqvwaX7pKlQP7JHgktA3DRcHS4AUCgltiEZtihy71+h3KBJ0JGNHZKQcn3z+6N19Sr613EAO7zQS6AeLNwAOV6VQAzFV5viRiIY+4FRZ6y6j5Hj7GIGkX46yV7aI6tG/8m10usHOnkjwj13r1F+pvun7RSz8DjAy8+8CmsiMSTvqaqEAWb5RduP21X37zGvuYaeRHflsFGqSAh06ziLeA3cjNKaru8MyhtisTkP0LlzAWpTKqz4llXspuNvirvhXwy+Gpk2GGdIpadaKol+BXhuqjDehcBGgDSFnT+qX7YikLftOUECvgT9ShKTg4xtEL4jnFymceVj0A3oIPAr6ogug5eeTx+XsGY8F/S8+zLMBxIPtyo3NkA3Xs038aHNM8jl25e2Z1OnVIDhGQoALsKQBc1/PNOJ8Tm1CkYnQbEv0BzeEFSa1LbhiV1oyQkf0BiJyngUOR+RAh5kFU6QfRjvYJa6j5HQ+TOszqZ+cHMbTcMktKpNQ7tBMm922G02mz3uKp0AcvcQ8hQ919EhE6Cw9QRDoBV0itOmHwivbOulBkQe5QNJnM5UBW8AxMhwg+RJNhmdaZ1Q+CH+t+URhSJuhp3XcQtvfFKlnIpsNP14up4VHIlpgXzedRh1mGCsp4jWD6Fp4wzVb+X3sWE0QD6Wyuimr/o="
